# Generated by Django 3.1 on 2020-08-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address_1',
            field=models.CharField(default='123 Foxtrot Street , TX, US', max_length=140, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address_2',
            field=models.CharField(default='233 Dromeestard Wageningen, the Netherlands', max_length=140, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Manhattan', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(default='John', max_length=140, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='John', max_length=140, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='New York', max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='JohnDoe101', max_length=100, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(default='P1023', max_length=20, verbose_name='Zip code'),
        ),
    ]
