# Generated by Django 3.1 on 2020-08-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200823_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('', 'Select'), ('USA', 'United States of America'), ('NG', 'Nigeria'), ('UK', 'United Kingdom'), ('NL', 'The Netherlands'), ('BE', 'Belgium'), ('GH', 'Ghana'), ('IN', 'India'), ('DE', 'Germany')], default='The Netherlands', max_length=200),
        ),
    ]
