# Generated by Django 3.1 on 2020-08-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Name of category', max_length=150)),
                ('category_pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-category_pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=150)),
                ('item_short_description', models.CharField(blank=True, max_length=255)),
                ('item_long_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_image', models.FileField(upload_to='gallery/')),
                ('item_domain_location', models.CharField(blank=True, max_length=160)),
                ('item_is_active', models.BooleanField(default=False)),
                ('item_pub_date', models.DateTimeField(auto_now_add=True)),
                ('item_updated_date', models.DateTimeField(auto_now_add=True)),
                ('item_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deutschstered.category')),
            ],
            options={
                'ordering': ['-item_pub_date'],
            },
        ),
    ]
