# Generated by Django 3.1 on 2020-08-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deutschstered', '0003_auto_20200818_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_draft_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_updated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
